export const products = [
    [
        {
            id: 1,
            name: "Петуния Софистика",
            alt: "Петуния Софистика F1",
            img: [
                require("./img/product/petunia/petunia.png"),
                require("./img/product/petunia/petuniaTwo.png"),
                require("./img/product/petunia/petuniaThree.png")
            ],
            price: 10,
            totalPrice: 10,
            to: "petunia",
            availability: "В наличии",
            priceFor: [1, 5, 10, 15],
            count: 1,
        },
        {
            id: 2,
            name: "Скор",
            alt: "Скор",
            img: [
                require("./img/product/skor/skor.png"),
                require("./img/product/skor/skorTwo.png"),
                require("./img/product/skor/skorThree.png"),
            ],
            price: 19,
            totalPrice: 19,
            to: "skor",
            availability: "В наличии",
            priceFor: [1, 4, 6],
            count: 1,
        },
        {
            id: 3,
            name: "Хорус",
            alt: "Хорус",
            img: [
                require("./img/product/horys/horys.png"),
                require("./img/product/horys/horysTwo.png"),
                require("./img/product/horys/horysThree.png"),
            ],
            price: 23,
            totalPrice: 23,
            to: "horys",
            availability: "В наличии",
            priceFor: [1, 3, 5],
            count: 1,
        },
        {
            id: 4,
            name: "Агрикола",
            alt: "Агрикола, удобрение для орхидей",
            img: [
                require("./img/product/agrikola/agrikola.png"),
                require("./img/product/agrikola/agrikolaTwo.png"),
                require("./img/product/agrikola/agrikolaThree.png"),
                require("./img/product/agrikola/agrikolaFour.png"),
            ],
            price: 31,
            totalPrice: 31,
            to: "agrikola",
            availability: "В наличии",
            priceFor: [1, 3, 6, 9],
            count: 1,
        },
    ],
    [
        {
            id: 5,
            name: "Агрикола",
            alt: "Агрикола, удобрение для орхидей",
            img: [
                require("./img/product/agrikola/agrikola.png"),
                require("./img/product/agrikola/agrikolaTwo.png"),
                require("./img/product/agrikola/agrikolaThree.png"),
                require("./img/product/agrikola/agrikolaFour.png"),
            ],
            price: 31,
            totalPrice: 31,
            to: "agrikola",
            availability: "В наличии",
            priceFor: [1, 3, 6, 9],
            count: 1,
        },
        {
            id: 6,
            name: "Хорус",
            alt: "Хорус",
            img: [
                require("./img/product/horys/horys.png"),
                require("./img/product/horys/horysTwo.png"),
                require("./img/product/horys/horysThree.png"),
            ],
            price: 23,
            totalPrice: 23,
            to: "horys",
            availability: "В наличии",
            priceFor: [1, 3, 5],
            count: 1,
        },
        {
            id: 7,
            name: "Скор",
            alt: "Скор",
            img: [
                require("./img/product/skor/skor.png"),
                require("./img/product/skor/skorTwo.png"),
                require("./img/product/skor/skorThree.png"),
            ],
            price: 19,
            totalPrice: 19,
            to: "skor",
            availability: "В наличии",
            priceFor: [1, 4, 6],
            count: 1,
        },
        {
            id: 8,
            name: "Петуния Софистика",
            alt: "Петуния Софистика F1",
            img: [
                require("./img/product/petunia/petunia.png"),
                require("./img/product/petunia/petuniaTwo.png"),
                require("./img/product/petunia/petuniaThree.png")
            ],
            price: 10,
            totalPrice: 10,
            to: "petunia",
            availability: "В наличии",
            priceFor: [1, 5, 10, 15],
            count: 1,
        },
    ],
    [
        {
            id: 9,
            name: "Скор",
            alt: "Скор",
            img: [
                require("./img/product/skor/skor.png"),
                require("./img/product/skor/skorTwo.png"),
                require("./img/product/skor/skorThree.png"),
            ],
            price: 19,
            totalPrice: 19,
            to: "skor",
            availability: "В наличии",
            priceFor: [1, 4, 6],
            count: 1,
        },
        {
            id: 10,
            name: "Петуния Софистика",
            alt: "Петуния Софистика F1",
            img: [
                require("./img/product/petunia/petunia.png"),
                require("./img/product/petunia/petuniaTwo.png"),
                require("./img/product/petunia/petuniaThree.png")
            ],
            price: 10,
            totalPrice: 10,
            to: "petunia",
            availability: "В наличии",
            priceFor: [1, 5, 10, 15],
            count: 1,
        },
        {
            id: 11,
            name: "Агрикола",
            alt: "Агрикола, удобрение для орхидей",
            img: [
                require("./img/product/agrikola/agrikola.png"),
                require("./img/product/agrikola/agrikolaTwo.png"),
                require("./img/product/agrikola/agrikolaThree.png"),
                require("./img/product/agrikola/agrikolaFour.png"),
            ],
            price: 31,
            totalPrice: 31,
            to: "agrikola",
            availability: "В наличии",
            priceFor: [1, 3, 6, 9],
            count: 1,
        },
        {
            id: 12,
            name: "Хорус",
            alt: "Хорус",
            img: [
                require("./img/product/horys/horys.png"),
                require("./img/product/horys/horysTwo.png"),
                require("./img/product/horys/horysThree.png"),
            ],
            price: 23,
            totalPrice: 23,
            to: "horys",
            availability: "В наличии",
            priceFor: [1, 3, 5],
            count: 1,
        },
    ],
    [
        {
            id: 13,
            name: "Петуния Софистика",
            alt: "Петуния Софистика F1",
            img: [
                require("./img/product/petunia/petunia.png"),
                require("./img/product/petunia/petuniaTwo.png"),
                require("./img/product/petunia/petuniaThree.png")
            ],
            price: 10,
            totalPrice: 10,
            to: "petunia",
            availability: "В наличии",
            priceFor: [1, 5, 10, 15],
            count: 1,
        },
        {
            id: 14,
            name: "Хорус",
            alt: "Хорус",
            img: [
                require("./img/product/horys/horys.png"),
                require("./img/product/horys/horysTwo.png"),
                require("./img/product/horys/horysThree.png"),
            ],
            price: 23,
            totalPrice: 23,
            to: "horys",
            availability: "В наличии",
            priceFor: [1, 3, 5],
            count: 1,
        },
        {
            id: 15,
            name: "Скор",
            alt: "Скор",
            img: [
                require("./img/product/skor/skor.png"),
                require("./img/product/skor/skorTwo.png"),
                require("./img/product/skor/skorThree.png"),
            ],
            price: 19,
            totalPrice: 19,
            to: "skor",
            availability: "В наличии",
            priceFor: [1, 4, 6],
            count: 1,
        },
        {
            id: 16,
            name: "Агрикола",
            alt: "Агрикола, удобрение для орхидей",
            img: [
                require("./img/product/agrikola/agrikola.png"),
                require("./img/product/agrikola/agrikolaTwo.png"),
                require("./img/product/agrikola/agrikolaThree.png"),
                require("./img/product/agrikola/agrikolaFour.png"),
            ],
            price: 31,
            totalPrice: 31,
            to: "agrikola",
            availability: "В наличии",
            priceFor: [1, 3, 6, 9],
            count: 1,
        },
    ],
]